// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CollateralFilingChartController from "./collateral_filing_chart_controller"
application.register("collateral-filing-chart", CollateralFilingChartController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndexFilingChartController from "./index_filing_chart_controller"
application.register("index-filing-chart", IndexFilingChartController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TaxlienFilingChartController from "./taxlien_filing_chart_controller"
application.register("taxlien-filing-chart", TaxlienFilingChartController)

import VolumeStatecodeChartController from "./volume_statecode_chart_controller"
application.register("volume-statecode-chart", VolumeStatecodeChartController)

import VolumeTypeChartController from "./volume_type_chart_controller"
application.register("volume-type-chart", VolumeTypeChartController)
